### ISSUE TITLE
ITMS-90809: Deprecated API Usage uiwebview

### ISSUE THREAD

**Issue by hermyth** [feixuwu/UE4EasyAds#10]
Hi, get this error when upload app to iOS App Store:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more 
information.

When disable the plugin in the project, not get any error from apple.

Can you fix this?

Thanks

**Comment by feixuwu** [comment]
it is not my code use uiwebview, I will check thirdparty sdk later

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by hermyth** [comment]
But when disable your plugin, no error, after just enable, and not need to use, got the error.

**Comment by feixuwu** [comment]
the plugin use some thirdparty sdk, I will check it when I got some time.

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by feixuwu** [comment]
OK, I found the problem, Unity ads include UIWebview,
I have submitted the fix, please clone the latest content and repackage your game, it should fixed.


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: hermyth <notifications@github.com>
发送时间: Wednesday, October 23, 2019 6:24:45 PM
收件人: feixuwu/UE4EasyAds <UE4EasyAds@noreply.github.com>
抄送: xufeiwu <feixuwu@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [feixuwu/UE4EasyAds] ITMS-90809: Deprecated API Usage uiwebview (#10)


But when disable your plugin, no error, after just enable, and not need to use, got the error.

―

**Comment by hermyth** [comment]
Get the same error from apple with this git version.

**Comment by feixuwu** [comment]
hi, sorry, it is my fault, my apple account out of date, so I can not confirm if chartboost or vungle sdk use UIWebview.
please try do this:
editor Plugins/EasyAds/Source/EasyAds/Build.cs
1、remove chartboost section:
           // chartboost
            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "CHAMoatMobileAppKit",														// Framework name
            "../ThirdParty/Frameworks/CHAMoatMobileAppKit.embeddedframework.zip")
            );

            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "Chartboost",														// Framework name
            "../ThirdParty/Frameworks/Chartboost.embeddedframework.zip")
            );

            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "ChartboostAdapter",														// Framework name
            "../ThirdParty/Frameworks/ChartboostAdapter.embeddedframework.zip")
            );
and then package it, check if it can pass.

2、remove vungle section:
  // vungle
            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "VungleAdapter",														// Framework name
            "../ThirdParty/Frameworks/VungleAdapter.embeddedframework.zip")
            );

            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "VungleSDK",														// Framework name
            "../ThirdParty/Frameworks/VungleSDK.embeddedframework.zip")
            );
and then package it, check if it can pass.
if remove chartboost or vungle can pass, please let me know, thanks very much!!

**Comment by feixuwu** [comment]
from vungle os sdk, I find the plugin sdk use 6.4.3 have the UIWebview problem, so please first remove vungle section from Build.cs, try it for a test

**Comment by hermyth** [comment]
Removed all, except Admob, still the same error.

`// Copyright 1998-2019 Epic Games, Inc. All Rights Reserved.

using UnrealBuildTool;
using System.IO;

public class EasyAds : ModuleRules
{
	public EasyAds(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
        PrivatePCHHeaderFile = "Public/EasyAds.h";

        PublicIncludePaths.AddRange(
			new string[] {
				// ... add public include paths required here ...
			}
			);
				
		
		PrivateIncludePaths.AddRange(
			new string[] {
				// ... add other private include paths required here ...
			}
			);
			
		
		PublicDependencyModuleNames.AddRange(
			new string[]
			{
				"Core",
				// ... add other public dependencies that you statically link with here ...
			}
			);
			
		
		PrivateDependencyModuleNames.AddRange(
			new string[]
			{
				"CoreUObject",
				"Engine",
				"Slate",
				"SlateCore",
				// ... add private dependencies that you statically link with here ...	
			}
			);
		
		
		DynamicallyLoadedModuleNames.AddRange(
			new string[]
			{
				// ... add any modules that your module loads dynamically here ...
			}
			);


        if (Target.Platform == UnrealTargetPlatform.Win32 || Target.Platform == UnrealTargetPlatform.Win64)
        {
            //PrivateIncludePaths.Add("Private/Windows");
        }
        else if (Target.Platform == UnrealTargetPlatform.Android)
        {
            PrivateDependencyModuleNames.Add("Launch");
            string PluginPath = Utils.MakePathRelativeTo(ModuleDirectory, Target.RelativeEnginePath);
            AdditionalPropertiesForReceipt.Add("AndroidPlugin", Path.Combine(PluginPath, "EasyAds_UPL.xml"));
        }
        else if(Target.Platform == UnrealTargetPlatform.IOS)
        {
            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "admobutil",														// Framework name
            "../ThirdParty/Frameworks/admobutil.embeddedframework.zip")
            );

            // admob
            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "GoogleMobileAds",														// Framework name
            "../ThirdParty/Frameworks/GoogleMobileAds.embeddedframework.zip")
            );

            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "GoogleAppMeasurement",														// Framework name
            "../ThirdParty/Frameworks/GoogleAppMeasurement.embeddedframework.zip")
            );

            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "GoogleUtilities",														// Framework name
            "../ThirdParty/Frameworks/GoogleUtilities.embeddedframework.zip")
            );

            PublicAdditionalFrameworks.Add(
            new UEBuildFramework(
            "nanopb",														// Framework name
            "../ThirdParty/Frameworks/nanopb.embeddedframework.zip")
            );

            
            PublicFrameworks.AddRange(
            new string[]
            {
            "EventKit",
            "CFNetwork",
            "GLKit",
            "MobileCoreServices",
            "SystemConfiguration",
            "MediaPlayer",
            "AdSupport",
            "CoreLocation",
            "MessageUI",
            "Security",
            "CoreTelephony",
            
            "Security",
            "StoreKit",
            "Foundation",
            "CoreGraphics",
            "WebKit",
            "AVFoundation",
            "UIKit"
            }
            );

            string PluginPath = Utils.MakePathRelativeTo(ModuleDirectory, Target.RelativeEnginePath);
            AdditionalPropertiesForReceipt.Add("IOSPlugin", Path.Combine(PluginPath, "EasyAds_IOS_UPL.xml"));
        }
        else if (Target.Platform == UnrealTargetPlatform.Mac)
        {
            //PrivateIncludePaths.Add("Private/Mac");
        }
        else
        {
            PrecompileForTargets = PrecompileTargetsType.None;
        }
    }
}
`

**Comment by feixuwu** [comment]
Please remove UIKit from the Build.cs

**Comment by feixuwu** [comment]
I guess the problem is you set ios min sdk version to 9?
would u please set it to 11 or 12?

**Comment by hermyth** [comment]
deleted uikit, still got the error, and the app instantly crash now when load, put back unlit . iOS is 11 minimum in UE4.23

**Comment by feixuwu** [comment]
hi, I have updated admob、unity、vungle sdk, please pull latest content and package again,
please let me know the result of upload to appstore, thanks very much

**Comment by hermyth** [comment]
Downloaded this version. Got the same error, and now crash the app after start.

**Comment by feixuwu** [comment]
ok,I will renew my apple account and submit a real game to test this weekend

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by feixuwu** [comment]
@hermyth , I have fixed the crash, and  I can submit the demo project with application loader on my mac,
so is it the problem of your project?

**Comment by feixuwu** [comment]
@hermyth  I can upload without warnning after remove chartboost and vungle from Build.cs,
but even if u recv the warnning from apple, u can still publish your game.

**Comment by hermyth** [comment]
Hi, thanks. I will test it today.

**Comment by hermyth** [comment]
Hi, no crash on ios, just still got the warning message (I hope apple accept in store). 
But now i have problem on android shipping package.
(Can package if disable the plugin)
There is my package log:

[Log.txt](https://github.com/feixuwu/UE4EasyAds/files/3783560/Log.txt)

**Comment by feixuwu** [comment]
the development package will success, right? the problem is Proguard about vungle, I will fix it today

**Comment by hermyth** [comment]
Yes, the development package works fine.
And how can enable other monetizing? I see only admob in the project settings, and on ios, not show up admob ads to me. (ID's are good)

**Comment by feixuwu** [comment]
I have submit a fix, please pull the latest content, should fix the android shipping package.
to add Unity and chartboost and vungle, u need go to your admob console, and add mediation group,
then u can  enable other monetizing.

IOS UIWebView warnning not stop applestore accept it, if u really want to remove the warnning, remove chartboost and vungle from Build.cs.

**Comment by feixuwu** [comment]
after upgrade chartboost ios sdk, IOS warnning disappear.
