### ISSUE TITLE
Video Reward: Invalid profile when resetting connection.

### ISSUE THREAD

**Issue by hllink** [feixuwu/UE4EasyAds#4]
Hello, i tested the video reward and it worked, but if i turn off my phone wifi and then turn it on, nothing happens when i call the PlayRewardedVideo action and that's following output logcat log:

`07-24 22:11:38.324   618   741 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only`
 complete stack:
![capturelogcat](https://user-images.githubusercontent.com/13907171/43174285-9b5e8e46-8f8f-11e8-8f7c-02ff44a39803.PNG)

**Comment by feixuwu** [comment]
this maybe the problem if admob sdk, I never tested disable wifi and then enable it.
I will do a test in the next few days
