### ISSUE TITLE
Rewardvideo callback not working on iOS

### ISSUE THREAD

**Issue by delcasda** [feixuwu/UE4EasyAds#5]
Hi,
I have my game published for Android and everything works fine, banner, interstatial and rewarded video but now that I am testing iOS all the ads run but I don't get a callback for the reward video so I never get the reward. The code and implementation is the very same for both, iOS and Android.

**Comment by feixuwu** [comment]
I will check it as soon as possible

?? Outlook for Android<https://aka.ms/ghei36>

________________________________
